### PR TITLE
Fix UB in `Arc::<MaybeUninit<_>>::write`

### LINKED ISSUE #41: `Arc::<MaybeUninit<T>>::write` is UB
`write` is defined like this:
```rust
impl<T> Arc<MaybeUninit<T>> {
    pub fn write(&mut self, val: T) -> &mut T {
        unsafe {
            let ptr = (*self.ptr()).data.as_mut_ptr();
            ptr.write(val);
            &mut *ptr
        }
    }
}
```

It writes to the inner value of the `Arc` even though unique access to `Arc` does **not** guarantee unique access to the inner value (b/c of clones). Here is a simple test case that fails under miri:

```rust
let mut uninit = Arc::new_uninit();
let clone = uninit.clone();

let x: &MaybeUninit<String> = &*clone;

// This write invalidates `x` reference
uninit.write(String::from("nonononono"));

// Read invalidated reference to trigger UB
let _ = &*x;
```
```text
error: Undefined Behavior: trying to reborrow <205779> for SharedReadOnly permission at alloc89625[0x8], but that tag does not exist in the borrow stack for this location
   --> src/lib.rs:107:5
    |
107 |     &*_x;
    |     ^^^^
    |     |
    |     trying to reborrow <205779> for SharedReadOnly permission at alloc89625[0x8], but that tag does not exist in the borrow stack for this location
    |     this error occurs as part of a reborrow at alloc89625[0x8..0x20]
    |
    = help: this indicates a potential bug in the program: it performed an invalid operation, but the Stacked Borrows rules it violated are still experimental
    = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
help: <205779> was created by a retag at offsets [0x8..0x20]
   --> src/lib.rs:103:36
    |
103 |     let _x: &MaybeUninit<String> = &*clone;
    |                                    ^^^^^^^
help: <205779> was later invalidated at offsets [0x8..0x20]
   --> src/arc.rs:247:23
    |
247 |             let ptr = (*self.ptr()).data.as_mut_ptr();
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: inside `ub` at src/lib.rs:107:5
note: inside closure at src/lib.rs:97:1
   --> src/lib.rs:97:1
    |
96  |   #[test]
    |   ------- in this procedural macro expansion
97  | / fn ub() {
98  | |     use core::mem::MaybeUninit;
99  | |
100 | |     let mut uninit = Arc::new_uninit();
...   |
107 | |     &*_x;
108 | | }
    | |_^
    = note: this error originates in the attribute macro `test` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### PR DESCRIPTION
**Pull request by WaffleLapkin**
Previously `write` would write even to a shared `Arc` which caused UB, as demonstrated by the `maybeuninit_ub_to_proceed` test.

This PR makes `write` panic on non-unique `Arc`s and adds similar functionality to `UniqueArc` where it's always safe.

Fixes #41

### CODE REVIEW

File: src/unique_arc.rs [hunk 1]
```diff
@@ -94,9 +94,43 @@ impl<T: ?Sized> UniqueArc<T> {
...
+
+        // Safety: caller guarantees that `arc` is unique,
+        //         `UniqueArc` is `repr(transparent)`
+        &mut *(arc as *mut Arc<T> as *mut UniqueArc<T>)
+    }
 }
 
 impl<T> UniqueArc<MaybeUninit<T>> {
+    /// Calls `MaybeUninit::write` on the contained value.
+    pub fn write(&mut self, val: T) -> &mut T {
```
Comment (WaffleLapkin) [inline src/unique_arc.rs:116]: I'm not sure what convention to use here... Normally arcs/boxes/etc use `this: &mut Self` so there is no conflict between inherent and deref methods. However, calling `MaybeUninit::write` (or `as_mut_ptr`, or `assume_init`) doesn't really make sense, so maybe we *do* want to shadow them? What do you think?

Comment (Manishearth) [reply src/unique_arc.rs:116]: You'd just call it UniqueArc::write, no?

Comment (WaffleLapkin) [reply src/unique_arc.rs:116]: I mean.. that's possible.

The question is only about "what API is better?". I've left the same as was on `Arc`, but can change it to `this: &mut Self`.

**Comment by Manishearth** [comment]
You have test failures in no_std mode btw
