### PR TITLE
Seprate HeaderSliceWithLength into checked and unchecked variants

### LINKED ISSUE #107: `ThinArc::with_arc_mut` is unsound
The length can be changed, allowing out-of-bounds access:
```rust
use triomphe::{Arc, ThinArc};

fn main() {
    let mut a = ThinArc::from_header_and_slice((), &[1, 2, 3]);
    a.with_arc_mut(|a| {
        let a = Arc::get_mut(a).unwrap();
        a.header.length = 1_000_000
    });
    println!("{:?}", a); // -> segfault
}
```
The whole `Arc` can be replaced, breaking ref-counts:
```rust
use triomphe::{Arc, ThinArc};

fn main() {
    let mut a = ThinArc::from_header_and_slice((), &[1, 2, 3]);
    let other = ThinArc::from_header_and_slice((), &[1, 2, 3]);
    let other = Arc::from_thin(other);
    let extracted = a.with_arc_mut(|a| std::mem::replace(a, other));
    println!("{:?}", a); // -> works
    drop(extracted);
    println!("{:?}", a); // -> use-after-free
}
```

---

I believe this can be contained with sufficiently enforced dynamic checks to prevent the UB… though it’s not a particularly elegant API anymore IMO, because I don’t think it’s possible to avoid even having to *abort* in some cases.

### PR DESCRIPTION
**Pull request by Manishearth**
Fixes #107

The breakage is limited to `with_mut()`, which now returns a `HeaderSliceWithLengthChecked` which has an immutable header.

Not fully happy with the resultant API, worth cleaning up in the next major release.

### CODE REVIEW

File: src/thin_arc.rs [hunk 1]
```diff
@@ -234,13 +222,60 @@ impl<H, T> Arc<HeaderSliceWithLength<H, [T]>> {
...
+        )
+    }
+
+    /// Converts an `Arc` into a `ThinArc`. This consumes the `Arc`, so the refcount
+    /// is not modified.
+    ///
+    /// # Safety
+    /// Assumes that the header length matches the slice length.
+    #[inline]
+    fn from_checked_header(a: Arc<HeaderSliceWithLengthChecked<H, [T]>>) -> Self {
```
Comment (steffahn) [inline src/thin_arc.rs:244]: Why is there a `Safety` comment?

File: src/thin_arc.rs [hunk 2]
```diff
@@ -234,13 +222,60 @@ impl<H, T> Arc<HeaderSliceWithLength<H, [T]>> {
...
+                )
+            },
+            phantom: PhantomData,
+        }
+    }
+
+    /// Converts a `ThinArc` into an `Arc`. This consumes the `ThinArc`, so the refcount
+    /// is not modified.
+    #[inline]
+    pub fn checked_header_from_thin(a: ThinArc<H, T>) -> Self {
```
Comment (steffahn) [inline src/thin_arc.rs:278]: I’m not *really* happy with the naming, haven’t thought of better alternatives yet.

The problem is that now there’s `Arc::from_thin` and `Arc::checked_header_from_thin`, and the latter just *sounds* more heavy, like there’s additional checking going on, even though the exact *opposite* is the case (you get something that needs *less* checking in order to convert back).

---

Actually, now I have an idea: how about the word becomes “protected”?

E.g. `HeaderSliceWithLengthProtected` instead of `HeaderSliceWithLengthChecked`. (And the `HeaderSliceWithLengthUnchecked` type synonym isn’t needed at all.)

Then we can have `Arc::from_thin` and `Arc::protected_from_thin`. That sounds less like additional “checking” is going on.

And we can have `ThinArc::with_arc` and `ThinArc::with_protected_arc` (the latter can also serve to be used internally an implementation that replaces the unsafe check-less `clone` from #76). We could even consider to *keep* `with_arc_mut` [with sufficient checks, i.e. under documented threat of abort] and add `with_protected_arc_mut` next to it, making the naming more consistent.

----

Or (coming back to naming) another idea is `HeaderSliceWithConstLen`, and thus `Arc::const_len_from_thin`, `ThinArc::with_const_len_arc` and `ThinArc::with_const_len_arc_mut`.

**Review by steffahn — COMMENTED** [review]
> Fixes #107

This addresses only half of #107. Switching out the whole `Arc`s is still a problem.

The `with_mut` callback can add a check for this. (Pointer equality, I guess? Actually, I suppose simply *unconditionally* writing back the new pointer could be okay.)

File: src/thin_arc.rs (hunk 2 above)
Comment (Manishearth) [reply src/thin_arc.rs:275]: Yeah I'm not happy with the naming either, this is just the naming that's stable. The unchecked variant should be more verbose.

Comment (Manishearth) [reply src/thin_arc.rs:275]: Protected seems fine for now. I don't like the implication of `const` here.

File: src/thin_arc.rs [hunk 3]
```diff
@@ -107,7 +107,11 @@ impl<H, T> ThinArc<H, T> {
 
         // Expose the transient Arc to the callback, which may clone it if it wants
         // and forward the result to the user
-        f(&mut transient)
+        let ret = f(&mut transient);
+        // It is possible for the user to replace the Arc entirely here. If so, we need to update the ThinArc as well
+        // Safety: We're still in the realm of Protected types so this cast is safe
+        self.ptr = transient.p.cast();
```
Comment (steffahn) [inline src/thin_arc.rs:113]: this writing back needs to move to some guard object's `Drop` for panic safety

Comment (Manishearth) [reply src/thin_arc.rs:113]: Hmm, I don't see an easy way of doing that: `f` borrows `transient` mutably so I can't have another handle to it active at the same time. Not quite sure how to get around that without introducing some Refcelly business.

Comment (Manishearth) [reply src/thin_arc.rs:113]: oh nvm figured it out. we have the guard object own it. easy

**Comment by steffahn** [comment]
Okay, finally starting another round of review. I’m wondering if `with_protected_arc` should be made public, I think it might be weird if the “more useful” (with stronger guarantees) protected version is only exposed to users of the mutable API.

**Comment by steffahn** [comment]
I wonder if `HeaderSliceWithLengthProtected` should just contain a slice directly, instead of `T: ?Sized`. I feel the invariant is hard(-ish) to formulate anyways. In the presence of unsizing coercions, a `[T; N]` in a `HeaderSliceWithLengthProtected` would also need to have correct length information.

Other types kind-of have no rules… except `str` is mentioned in the current docs.

Ultimately, `HeaderSliceWithLengthProtected` is a tool for a sound API of `ThinArc` and `ThinArc` doesn't support anything but `[T]`. Even the `str` case seems relatively irrelevant, because `ThinArc` doesn't support it.

**Comment by steffahn** [comment]
> I wonder if `HeaderSliceWithLengthProtected` should just contain a slice directly, instead of `T: ?Sized`.

@Manishearth I've tried this out myself, so you don't have to; see #110 ;-)

**Comment by steffahn** [comment]
Other than the suggestions above, this PR looks good to me.

**Review by steffahn — APPROVED** [review]

**Comment by Manishearth** [comment]
Merging this first, I'll get around to your changes soon. The reason I didn't want to make HeaderSliceWithLengthProtected  contain a slice directly was that I was worried about the `[T; 0]` layout changes: AIUI Rust `CoerceUnsized` guarantees equivalent layout for `Foo<[T]>` vs `Foo<[T; N]>` but it does not do that for different types. If your changes can make that part still safe I'm all for it, I don't want the protected type to be overly generic.
